(()=>{
const state={stream:null,reader:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null||v===''?'—':`KES ${Number(v).toLocaleString()}`;
async function lookup(code,out){const q=String(code||'').trim();if(!q)return;out.innerHTML='<div class="notice">Code detected. Looking up voucher…</div>';try{const r=await fetch('/api/redeem-voucher',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:q,action:'lookup'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Voucher not found');const v=d.voucher||{};out.innerHTML=`<div class="lookup-result"><span class="pill">${esc(v.status||'unredeemed')}</span><strong>${esc(v.buyerName||'Voucher found')}</strong><div class="lookup-grid"><div><small>Reference</small>${esc(v.ref||v.code||q)}</div><div><small>Customer</small>${esc(v.buyerName||v.buyerEmail||v.buyerPhone||'—')}</div><div><small>Service</small>${esc(v.serviceName||v.type||'—')}</div><div><small>Value</small>${money(v.value)}</div></div></div>`}catch(e){out.innerHTML=`<div class="notice error"><strong>Voucher lookup failed</strong><p>${esc(e.message)}</p></div>`}}
function stop(remove=true){state.reader?.reset?.();state.reader=null;state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;const video=document.querySelector('#rica-video');if(video?.srcObject){video.srcObject.getTracks().forEach(t=>t.stop());video.srcObject=null}if(remove)document.querySelector('.rica-scanner')?.remove()}
async function start(){const video=document.querySelector('#rica-video'),stateEl=document.querySelector('#rica-scan-state'),out=document.querySelector('#rica-scan-result');if(!video||!stateEl||!out)return;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('This browser does not expose camera access.');if(video.srcObject)video.srcObject.getTracks().forEach(t=>t.stop());state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=state.stream;await video.play();stateEl.textContent='Camera ready — point it at the voucher QR/barcode.';if(!window.ZXingBrowser){stateEl.textContent='Loading QR/barcode scanner…';await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/@zxing/browser@0.1.5/umd/zxing-browser.min.js';s.onload=resolve;s.onerror=()=>reject(Error('Could not load the barcode scanner'));document.head.appendChild(s)})}const reader=new ZXingBrowser.BrowserMultiFormatReader();state.reader=reader;await reader.decodeFromVideoDevice(undefined,video,(result)=>{if(result){const raw=result.getText();reader.reset();state.reader=null;lookup(raw,out)}})}catch(e){stateEl.textContent=`Camera could not start: ${e.message||'permission denied'}. Use manual lookup below.`;console.warn(e)}}
window.ricaStartScanner=start;window.ricaStopScanner=stop;window.ricaVoucherLookup=lookup;
const observer=new MutationObserver(()=>{const modal=document.querySelector('.rica-scanner');if(modal&&!modal.dataset.scannerFix){modal.dataset.scannerFix='1';setTimeout(start,150);modal.querySelector('#rica-close')?.addEventListener('click',()=>stop(),{once:true})}});observer.observe(document.body,{childList:true,subtree:true});
})();