import React from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, CalendarDays, MessageSquare, Ticket, ShoppingBag, Users, UserCircle, Activity, LogOut, RefreshCw } from 'lucide-react';
import './styles.css';

const nav=[['Overview',LayoutDashboard],['Bookings',CalendarDays],['Messages',MessageSquare],['Vouchers',Ticket],['Orders',ShoppingBag],['Customers',Users],['Staff & Users',UserCircle],['Activity',Activity]];
async function api(path){const r=await fetch(path,{credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
const fmt=n=>Number(n||0).toLocaleString();
function App(){const [section,setSection]=React.useState('Overview');const [data,setData]=React.useState(null);const [error,setError]=React.useState('');const load=React.useCallback(async()=>{setError('');try{const [stats,bookings,orders]=await Promise.all([api('/api/dashboard-stats'),api('/api/dashboard-bookings?upcoming=1'),api('/api/dashboard-orders')]);setData({stats,bookings:bookings.bookings||bookings.results||[],orders:orders.orders||orders.results||[]})}catch(e){setError(e.message)}},[]);React.useEffect(()=>{load()},[load]);return <div className="rica-shell"><aside><div className="logo"><img src="/assets/img/logo.png"/><span>Rica Spa<small>Admin workspace</small></span></div><div className="label">Workspace</div>{nav.slice(0,6).map(([n,I])=><button key={n} className={section===n?'active':''} onClick={()=>setSection(n)}><I size={17}/>{n}</button>)}<div className="label">Administration</div>{nav.slice(6).map(([n,I])=><button key={n} className={section===n?'active':''} onClick={()=>setSection(n)}><I size={17}/>{n}</button>)}<div className="account"><div className="avatar">R</div><div><b>Rica Admin</b><small>Superuser</small></div><LogOut size={16}/></div></aside><main><header><div><span>RICA SPA / ADMIN</span><h1>{section}</h1></div><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={18}/></button></header><div className="page">{error&&<div className="error">{error}</div>}{section==='Overview'?<Overview data={data}/>:<Section name={section} data={data}/>}</div></main></div>}
function Overview({data}){const s=data?.stats||{};return <><div className="notice"><div><small>RICA SPA OPERATIONS</small><h2>Good to see you.</h2><p>Your operational workspace at a glance.</p></div><div className="mark">R</div></div><div className="cards">{[['Bookings',s.totalBookings??s.bookings],['Pending',s.pendingBookings??s.pending],['Orders',s.totalOrders??s.orders],['Revenue',`KES ${fmt(s.revenue??s.totalRevenue)}`]].map(([a,b])=><div className="card" key={a}><small>{a}</small><strong>{typeof b==='object'?fmt(b.count??b.total):fmt(b)}</strong><span>Live D1 data</span></div>)}</div><div className="panel"><div className="panel-title"><div><small>UPCOMING</small><h2>Bookings</h2></div></div><Table rows={data?.bookings||[]} columns={['name','service','preferred_date','preferred_time','status']}/></div></>}
function Section({name,data}){if(name==='Bookings')return <div className="panel"><div className="panel-title"><div><small>APPOINTMENTS</small><h2>Booking requests</h2></div></div><Table rows={data?.bookings||[]} columns={['name','service','preferred_date','preferred_time','status']}/></div>;if(name==='Orders')return <div className="panel"><div className="panel-title"><div><small>SALES</small><h2>Voucher orders</h2></div></div><Table rows={data?.orders||[]} columns={['ref','email','amount','status','created_at']}/></div>;return <div className="panel"><div className="panel-title"><div><small>RICA SPA</small><h2>{name}</h2></div></div><div className="empty"><h3>{name} workspace</h3><p>This section is ready for the corresponding template component and API integration.</p></div></div>}
function Table({rows,columns}){return <div className="table-wrap">{rows.length?<table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.ref||i}>{columns.map(c=><td key={c}>{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'—')}</td>)}</tr>)}</tbody></table>:<div className="empty"><h3>No records found</h3><p>The dashboard is querying live D1 data; there are currently no records returned for this view.</p></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);